version: '4.15.0'
services:
    localstack:
      container_name: "${LOCALSTACK_DOCKER_NAME-sqs_queue}"
      image: localstack/localstack:latest
      restart: always
      ports:
        - "4566:4566"   # LocalStack Gateway
      environment:
        - SERVICES = sqs, sns
        - DEBUG=${DEBUG-}
        - DOCKER_HOST=unix:///var/run/docker.sock
        - DEFAULT_REGION = us-east-1
        - EDGE_PORT=4566
        - LEGACY_INIT_DIR=1.
        - HOSTNAME_EXTERNAL=localstack
      volumes:
        - ./localstack_bootstrap:/docker-entrypoint-initaws.d/
        - /var/lib/localstack.
        - /var/run/docker.sock:/var/run/docker.sock

    db:
      image: postgres:latest
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
      ports:
        - '5432:5432'
      volumes:
        - db:/var/lib/postgresql11/data
        - ./db/init-scripts.sql:/docker-entrypoint-initdb.d/scripts.sql
volumes:
  db:
    driver: local
